Add Question Service
CS3219-AY2425S1/cs3219-ay2425s1-project-g50 pull request #113
Opened 2024-09-20 13:57 UTC by dylkaw

This PR resolves #14 and resolves #50.

## Overview
This PR sets up the base for the FastAPI Question Service. In this PR, basic Create and Read endpoints have been created.

## Setup
1. In the `question-service` directory, run `python -m venv .venv` to create a virtual environment.
2. Run `source .venv/bin/activate` to activate the virtual environment.
3. Run `pip install -r requirements.txt` to install all necessary dependencies.
4. Ensure you have a `.env` file with the question service mongoDB uri. 
5. To start the service, run `fastapi dev app.py`

Note: For VSCode to properly detect the venv, open the project with `question-service` as the root directory. If not, VSCode will not detect the venv properly and will scream at you for everything. 

## Backend changes
1. `'QuestionModel` created, it has fields title, description, category and complexity. id is not necessary as it is automatically generated by mongoDB on create.
2. `create_question` and `get_questions` endpoints created. 

Question service will be served at `http://127.0.0.1:8000` and you will be able to test requests directly on the Swagger UI at `http://127.0.0.1:8000/docs`.

2024-09-20 15:58 UTC, wr1159 commented
Can you add a README.md for how to set it up? would be greatly appreciated thanks

2024-09-20 17:10 UTC, jq1836 requested changes
Require some minor changes to support Windows OS. Apart from that, LGTM!

2024-09-20 17:10 UTC, jq1836 commented on question-service/requirements.txt
> +uvloop==0.20.0
Need to remove uvloop, otherwise wouldn't work on Windows OS

2024-09-20 17:12 UTC, jq1836 commented on question-service/README.md
> +2. Run `source .venv/bin/activate` to activate the virtual environment.
Btw, this is different for Windows, supposed to just run .venv/Scripts/activate, apart from that, its the same

2024-09-21 03:08 UTC, SelwynAng reviewed
Perhaps can follow a project structure as shown here https://medium.com/@amirm.lavasani/how-to-structure-your-fastapi-projects-0219a6600a8f

2024-09-21 04:25 UTC, SelwynAng approved these changes
LGTM!

2024-09-23 06:47 UTC, jq1836 approved these changes
LGTM!

2024-09-23 10:01 UTC, merged